### ISSUE TITLE
Recognize filenames embedded in markup

### ISSUE THREAD

**Issue by david-christiansen** [myuhe/quick-preview.el#2]
It would be nice to be able to use `quick-preview` in AUCTeX to look at pictures. For example, getting a preview of `./fig2.png` in the local directory of the file:

```
\includegraphics{fig2.png}
```

Even putting spaces around fig2.png just causes GNOME sushi to pop up with a black box and spinning wheel.

**Comment by david-christiansen** [comment]
Similarly with filenames in strings in Elisp code. It looks like `quick-preview--get-filename` is including the quotes.

**Comment by david-christiansen** [comment]
Cool package, BTW - I look forward to it getting even better!

**Comment by myuhe** [comment]
Thanks.
`quick-preview--get-filename` uses `ffap-file-at-point`, It uses generally. 
So, I Should not change  function of `ffap-file-at-point` .
Try to hack `ffap-file-at-point`, [EmacsWiki: Find File At Point](http://emacswiki.org/emacs/FindFileAtPoint) may help you.
